[package]
name = "doing-some-cardano-with-rust"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hex = "0.4.3"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }

blockfrost = "1.0.1"

pallas = { version = "0.22.0", features = ["unstable"] }
